[lint]
select = [
    "I",
    "ICN",
    "LOG",
    "G",
    "SIM",
    "TID",
    "C4",
    "A",
    "E",
    "F",
    "C90",
    "N",
    "PERF",
    "D",
    "PL",
    "FURB",
    "RUF",
    "PTH",
    "S",
    "FA",
    "B",
]

ignore = [
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
]

